### ISSUE TITLE
it has no a App.framework after build ios-framework --cocoapods'

### ISSUE THREAD

**Issue by godd113** [duytq94/demo-integrate-flutter#2]
Hello, I downloaded and build your project, and in the step 'flutter build ios-framework --cocoapods'
It's output build 

Building frameworks for com.example.duyfluttermodule in debug mode...
 ├─Creating Flutter.podspec...                                       3ms
 ├─Building App.xcframework...                                      8.3s
 └─Moving to build/ios/framework/Debug                              56ms
Building frameworks for com.example.duyfluttermodule in profile mode...
 ├─Creating Flutter.podspec...                                       2ms
 ├─Building App.xcframework...                                     18.1s
 └─Moving to build/ios/framework/Profile                            24ms
Building frameworks for com.example.duyfluttermodule in release mode...
 ├─Creating Flutter.podspec...                                       1ms
 ├─Building App.xcframework...                                     14.1s
 └─Moving to build/ios/framework/Release                            19ms

My problem is it has no a App.framework. so in Xcode project it is not found App.framework

Can you help me to fix this solve?

Thank you

![Screenshot 2566-04-19 at 15 17 26](https://user-images.githubusercontent.com/52393880/233013239-cfe1cac9-f78c-4591-8484-12ad0f1fc27d.png)

**Comment by duytq94** [comment]
Yes, I am stuck with the same problem, it seems many things have changed after a long time.
Still, trying to fix it.

**Comment by duytq94** [comment]
I found that issue is the new Flutter SDK will generate `App.xcframework` instead of `App.framework` when you run `flutter build ios-framework --cocoapods`
So if you drag the debug `App.xcframework` and remove the old, to `Embed Frameworks` & `Link Binary With Libraries` at `Build Phases` it will solve the issue.
But the above solution is temporary because it hardcode to use debug framework, I still found the way to embed the framework depends on $CONFIGURATION so it will choose de debug or release framework automatically.

**Comment by duytq94** [comment]
I found that issue is the new Flutter SDK will generate `App.xcframework` instead of `App.framework` when you run `flutter build ios-framework --cocoapods`
So if you drag the debug `App.xcframework` and remove the old, to `Embed Frameworks` & `Link Binary With Libraries` at `Build Phases` it will solve the issue (checkout `fix-ios` branch I just push)
But the above solution is temporary because it hardcode to use debug framework, I still found the way to embed the framework depends on $CONFIGURATION so it will choose de debug or release framework automatically.

**Comment by duytq94** [comment]
Fixed at https://github.com/duytq94/demo-integrate-flutter/pull/3
